project_id = "moeegphrlhtuovqtgrci"

[functions.api-auth-me]
verify_jwt = false

[functions.api-keys-manage]
verify_jwt = false

[functions.scrape]
verify_jwt = false

[functions.api-usage]
verify_jwt = false

[functions.crawl]
verify_jwt = false

[functions.crawl-worker]
verify_jwt = false

[functions.map]
verify_jwt = false

[functions.extract]
verify_jwt = false
